// Code generated by inspc. DO NOT EDIT.
// source: github.com/koykov/inspector/testobj

package testobj_ins

import (
	"github.com/koykov/inspector"
)

func init() {
	inspector.RegisterInspector("TestFinance", TestFinanceInspector{})
	inspector.RegisterInspector("TestFlag", TestFlagInspector{})
	inspector.RegisterInspector("TestHistory", TestHistoryInspector{})
	inspector.RegisterInspector("TestObject", TestObjectInspector{})
	inspector.RegisterInspector("TestPermission", TestPermissionInspector{})
}
