// Code generated by inspc. DO NOT EDIT.
// source: github.com/koykov/inspector/testobj

package testobj_ins

import (
	"github.com/koykov/inspector"
)

func init() {
	inspector.RegisterInspector("TestFinance", TestFinanceInspector{})
	inspector.RegisterInspector("TestFlag", TestFlagInspector{})
	inspector.RegisterInspector("TestFloatPtrSlice", TestFloatPtrSliceInspector{})
	inspector.RegisterInspector("TestFloatSlice", TestFloatSliceInspector{})
	inspector.RegisterInspector("TestHistory", TestHistoryInspector{})
	inspector.RegisterInspector("TestObject", TestObjectInspector{})
	inspector.RegisterInspector("TestObject1", TestObject1Inspector{})
	inspector.RegisterInspector("TestPermission", TestPermissionInspector{})
	inspector.RegisterInspector("TestStringFloatMap", TestStringFloatMapInspector{})
	inspector.RegisterInspector("TestStringFloatPtrMap", TestStringFloatPtrMapInspector{})
	inspector.RegisterInspector("TestStringPtrFloatPtrMap", TestStringPtrFloatPtrMapInspector{})
}
